apiVersion: batch/v1
kind: CronJob
metadata:
  name: report-generator
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: hello
            image: bash
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - echo :report generation done"
          restartPolicy: OnFailure

